### ISSUE TITLE
Unable to decode GAC correctly

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#14]
**Describe the bug**
I had a very clear constellation - live decoded. I then ran it through LeanHRPT Decode and it outputted garbage. I had (for some reason) only the HRIS instrument, and the satellite name was NOAA-19. I received GAC from NOAA-18. Any ideas?

**Comment by Xerbo** [comment]
DSB support was added in v0.7.0 and for some reason GAC is being identified as that
