### ISSUE TITLE
Live decoding

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#21]
**Describe the feature you would like**
Would it be possible to create a live decoding feature? It would be really useful!

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by Xerbo** [comment]
Anything past a basic unprocessed channel view would require significant work, would just that be fine?

**Comment by zeke800** [comment]
Yes!! Thank you so much! I would love this feature :)
