### ISSUE TITLE
Backwards GAC samples

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#23]
A while back, I forgot to send some files from backwards GAC!

This is from NOAA-18, a GAC dump transmitted on 1698MHz. Unfortunately, the satellite was quite low on the horizon, and my 1m offset dish can't pull in much of a signal. Either way, I would appreciate it if you could implement a decoder.

Thank you!

[noaagacjuly12_test.zip](https://github.com/Xerbo/LeanHRPT-Decode/files/9103057/noaagacjuly12_test.zip)

**Comment by zeke800** [comment]
Thank you very much!!

**Comment by zeke800** [comment]
Hmm... something is wrong here...

LeanHRPT
![image](https://user-images.githubusercontent.com/82127189/178849541-dca9f03a-2546-4494-848e-4dba850d7ed2.png)
SatDump
![image](https://user-images.githubusercontent.com/82127189/178849548-52445ab1-c87b-4213-8f92-d7e4899d6a73.png)

**Comment by zeke800** [comment]
Seems mirrored?

**Comment by Xerbo** [comment]
Sorry about the delays but something is wrong with my parity checking code (use for checking timestamps, and thus geomanipulation) and I haven't been able to track it down

**Comment by Xerbo** [comment]
Flat out removed the parity checking (GAC only, not HRPT) in f368b64 although that means noisy passes will break the projector/map overlays
