### ISSUE TITLE
Projection issues

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#24]
Consistently happening for a few passes now of different satellites. Also, GAC projection doesn't seem to work, only shows a black square. 

![image](https://user-images.githubusercontent.com/82127189/180071043-df051684-d719-4ad5-a2e0-83c0dece5561.png)

Thank you for all of the bug fixes!

**Comment by Xerbo** [comment]
Could you send some example files which this happens on
