### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#25]
On the [WMO OSCAR database](https://space.oscar.wmo.int/satellites/view/meteor_m_n2_2), Meteor M2-2 has all sorts of cool instruments, such as a Synthetic Aperture Radar, and even an imager that transmits NIR and **true color** images (KMSS)!!! 

My question is, is the data from these instruments in the HRPT data? If not, where is it broadcast? X band dumps? I would expect it to be in the HRPT due to the "realtime broadcast" service, however, x band seems more likely due to the data rates. 

EDIT: Apparently the data rate is over 60 Mbps, so not HRPT.

On a separate note - what software do you use to analyze the bin files?

**Comment by Xerbo** [comment]
All HRPT carries is MSU-MR, MTVZA, SSPD and BIS-M ([source](http://planet.iitp.ru/retro/index.php?lang=en&page_type=spacecraft&page=meteor_m_n2_structure_1)). And for analysing binary files I use [hobbits](https://github.com/Mahlet-Inc/hobbits) and [ImHex](https://github.com/WerWolv/ImHex).
