### ISSUE TITLE
Meteor-M CADU support

### ISSUE THREAD

**Issue by RAD750** [Xerbo/LeanHRPT-Decode#26]
**Describe the bug**

Loading a CADU file produced by SatDump and obtained from the Meteor-M series of satellites, immediately crashes LeanHRPT-decode with a segmentation fault.

**To Reproduce**
1. Download either of these two CADU files obtained from SatDump v0.0.39: [directory listing](https://regulus.a-centauri.com/filedump/HRPT/METEORN2-2/)
2. Open LeanHRPT-Decode
3. Load the CADU file via File -> Open
4. LeanHRPT-Decode crashes immediately. If executed from command line, a segmentation fault message appears. Nothing else is output.

This happens both with the Meteor-M N2 (the one with LRPT still active) and Meteor-M N2-2. A file for Meteor-M N2 can be found in the above directory listing as well (go back a level to find other satellites). 

I should mention that LeanHRPT opens without any problem all other files obtained from SatDump, but from other satellites, such as METOP or NOAA POES.

The problem also happens under Windows, although of course there is no indication about a segmentation fault, the program just closes immediately.

**Expected behavior**
The CADU file would get opened and processed.

**Platform**
 - Linux Pop!_OS (based on Ubuntu) 22.04, both on laptop and desktop.
 - Windows 10 64 bit 21H1 build 19043.928, virtualized under VMWare Player 16 on the desktop
 
**Version**
Laptop: v0.8.0-rc2 (Ubuntu Jammy package)
Desktop: (compiled from source): v0.8.0-rc2-12-g4789b1a
Virtual Machine: v0.8.0-rc2

On the desktop the compiling software was all installed from official repositories of Ubuntu 22.04.

In case it is needed, specifications of the two computers.
Laptop: Lenovo Thinkpad X260 (Intel i5-6200u, 8GB RAM, integrated Intel HD Graphics 520) 
Desktop: Dell Optiplex 9010 (Intel i5-3470, 16 GB RAM, dedicated AMD Radeon RX570)

Thanks in advance!

**Comment by Xerbo** [comment]
I had removed Meteor HRPT "CADU" reading support in the past as it proved difficult to differentiate it from other satellites as it doesn't follow any CCSDS standards. The above commit doesn't add support but at least fixes the segfault.

I will have a think about this over the next couple of days

**Comment by RAD750** [comment]
Just a dumb idea, but couldn't you add a question like "Is this a Meteor CADU" and depending on the user answer, decode the file appropriately?
