### ISSUE TITLE
Missing step or dependency in build/install instructions

### ISSUE THREAD

**Issue by ai6yr** [Xerbo/LeanHRPT-Decode#28]
**Describe the bug**
Following the build/install instructions on Ubuntu 20.04.5, run into the following error message:
ai...ner:~/LeanHRPT-Decode/build$ make
[  2%] Automatic MOC and UIC for target LeanHRPT-Decode
[  2%] Built target LeanHRPT-Decode_autogen
[  5%] Building CXX object CMakeFiles/LeanHRPT-Decode.dir/src/commandline.cpp.o
/home/...../LeanHRPT-Decode/src/commandline.cpp: In function ‘ulong str2ulong(QString)’:
/home/..../LeanHRPT-Decode/src/commandline.cpp:38:14: error: ‘class QLocale’ has no member named ‘toULong’

**To Reproduce**
New (scratch) install of Ubuntu 20.04.5
Follow instructions on https://github.com/Xerbo/LeanHRPT-Decode

**Expected behavior**
Expected make would build

**Platform**
Linux .... 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Version**
origin/master

**Comment by Xerbo** [comment]
What version of Qt are you using, LeanHRPT requires at least 5.14 and if I remember correctly Ubuntu 20.04 doesn't provide that.

You can download Qt with https://github.com/miurahr/aqtinstall and then pass `-DCMAKE_INSTALL_PREFIX=/path/to/qt/5.x.x/` to cmake
