### ISSUE TITLE
[QUESTION] How do I add new composites?

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Decode#8]
Hi! I just made a few composites with the new sensors available... how would I add them to the software? I have an updated 'presets.ini' file and would like to add it to the main repository. 

Thanks!

**Comment by Xerbo** [comment]
Create a fork of this repository, add your fixes/additions as usual. And then commit onto a new branch:

![image](https://user-images.githubusercontent.com/23143405/150424310-be5ba6f1-16b3-470d-918f-ffcfb78be6cc.png)

After that open a pull request and you are all done.

**Comment by zeke800** [comment]
Thanks! But how do I insert it into the default presets.ini file?

**Comment by Xerbo** [comment]
Could you please clarify what you mean?
